### ISSUE TITLE
[SDL version] lag when clicking on keys

### ISSUE THREAD

**Issue by MatMoul** [gwenhael-le-moine/x48ng#11]
Hi,

Since updating from version 0.13.0 to version 0.22.0, the UI is very laggy.
In fact, when I click on a key, it takes more than 2 seconds for the interface to react.
There are also the DE graphic effects that are disabled when launching from the terminal.

I noticed this on my ArchLinux with KDE/PLASMA.
Then I tried to reproduce this on an Ubuntu 23.04 and had no issue.
Finally I tested it on a Kubuntu 23.04 and the same issue happened.

SDL1.2 seem does not work well with KDE/PLASMA

**Comment by gwenhael-le-moine** [comment]
I can see it here in Sway too… I'm so used to testing it with the keyboard that I hadn't noticed.
(Technically it's using SDL2 through the sdl12-compat layer.)

In fact the problem is present in the original sdl port.

Need to investigate more

**Comment by gwenhael-le-moine** [comment]
I might be wrong but it seem not all keys are equally affected, some are responsive while others are not.

I suspect `SDLCoordinateToKey()` (`ui_sdl.c` line 1431). That function and its cousin `SDLKeyToKey()` look like they could be optimized. Will look into it.

**Comment by gwenhael-le-moine** [comment]
I pushed an update to change the way keys are found from keyboard or mouse but it doesn't seem to improve.

Next step is to look into `ui__get_event()` in `ui_sdl.c` line 2728

**Comment by MatMoul** [comment]
I confirm, the problem persists.

I also noticed a difference in the fonts of the buttons (first X11, second SDL) :

![x11](https://github.com/gwenhael-le-moine/x48ng/assets/13386289/b1eece43-c2cb-4d82-bfa5-42cc36b23f24) ![sdl](https://github.com/gwenhael-le-moine/x48ng/assets/13386289/260543ba-5940-45fc-b4c8-36d3e8a72ea7)

**Comment by gwenhael-le-moine** [comment]
Yes, the font used is different.

I pushed 0.23.0 which brings back the x11 frontend. SDL is still the default but passing `GUI=x11` to `make` and `make install` builds and install the x11 version (install for copying `dist/X48NG.ad` to `/etc/X11/app-defaults/X48NG`

`ui_sdl.c` and `ui_x11.c` will see some refactoring to have less duplicated code between the two and the arguments parsing is still a bit messy and med some love too.

**Comment by MatMoul** [comment]
Thanks for the changes...

SDL seems a good solution but after some research it seems that the bugs were only fixed in version 2 (not sure).

I now have a few other problems but I have to concentrate on my job for the next few days.

Version 0.24.1 with x11 as default and new full dependency:
Functional but when I click on a button, the LCD does not refresh as it should.
On the next click, I see my first click but not the latest.

Version 0.25 with x11 as default and new full dependency:
Construction: OK
But return an error when launching the installed binary.

```
~ $ x48ng -V
verbose = 1
useTerminal = 1
useSerial = 0
throttle = 0
initialize = 0
resetOnStartup = 0
serialLine = /dev/ttyS0
romFileName = rom
homeDirectory = .x48ng
read /home/user/.x48ng/rom
read /home/user/.x48ng/hp48
read /home/user/.x48ng/ram
read /home/user/.x48ng/port1
read /home/user/.x48ng/port2
wire connection on /dev/pts/4
using XShm extension.
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Value in failed request:  0x53
  Serial number of failed request:  34
  Current serial number in output stream:  42
```

I'll try to come back in a few days with new issues ;-)

**Comment by gwenhael-le-moine** [comment]
I pushed 0.25.1 in which I uncommented X Visual managing code (see the new `--x11-visual=<visual>` option). I guess it picked `truecolor` in your system which show your error. Hopefully setting visual to `default` as default allows x48ng to start for you.

**Comment by MatMoul** [comment]
Hi and thank for your work,
The X11 version works again!
And I see lots of changes like a dependency on lua and a new config folder ;)

**Comment by MatMoul** [comment]
Hi this issue can be closed for me.

x48ng --sdl seems to work, but when closing the window there is a wait time.

I will open another issue if necessary.

Thank you for your work!
